    <link rel="stylesheet" href="{{asset('assets_client/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets_client/css/all.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets_client/css/animate.css')}}">
    <link rel="stylesheet" href="{{asset('assets_client/css/flaticon.css')}}">
    <link rel="stylesheet" href="{{asset('assets_client/css/magnific-popup.css')}}">
    <link rel="stylesheet" href="{{asset('assets_client/css/odometer.css')}}">
    <link rel="stylesheet" href="{{asset('assets_client/css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets_client/css/owl.theme.default.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets_client/css/nice-select.css')}}">
    <link rel="stylesheet" href="{{asset('assets_client/css/main.css')}}">